/**
 * How far "louder" can actually go, and by what mechanism.
 *
 * The app's volume setting is a multiplier UNDER the device volume, so at
 * 1.0 it is already passing audio through unattenuated. Going above that is
 * real amplification, and the platform is unusually strict about it -- these
 * ceilings were measured, not assumed:
 *
 *   - `HTMLMediaElement.volume = 2`      -> THROWS IndexSizeError
 *   - `SpeechSynthesisUtterance.volume = 2` -> silently clamps to 1
 *   - `GainNode.gain.value = 4`          -> accepted
 *
 * SO ABOVE 1.0 THERE IS NOTHING LEFT FOR THE VOICE, by either path. Live
 * `speechSynthesis` clamps in the browser and no app code moves that. The
 * recorded clips could be routed through a GainNode, and were, until the
 * phone said what that costs on 2026-10-02:
 *
 *   "You have fifteen. Dealer shows five."   3029ms at 100%, 4455ms at 200%
 *   "You have ace, seven. Dealer shows six." 3099ms at 100%, 7687ms at 150%
 *
 * 150% was worse than 200%, so the damage is not proportional to the gain and
 * is not the gain; nor is it clipping, since the clips peak at 0.34-0.81 and
 * nothing reaches full scale even doubled. It is the route itself: 24kHz files
 * resampled live into a graph clocked by hardware whose rate the open
 * microphone keeps moving. Choppy, then silent. See audio/clips.ts.
 *
 * What the headroom above 1.0 still buys is the CHIMES (`chimePeak`), which
 * are generated by an oscillator already inside the graph -- no media element,
 * no resampling, nothing to damage -- and which are the cue that tells the
 * driver the microphone is open. That is worth keeping. The voice is a matter
 * for the hardware buttons and the output route.
 */

/**
 * 200%, and it is the CHIME ceiling now rather than the voice's.
 *
 * `chimePeak` is 0.5 at unity, so 2.0 is exactly the point where a chime
 * reaches full scale; past it the tone would clip for no extra loudness. The
 * number is a measured ceiling, not a preference, which is the answer to "is
 * 2x a hard cap?" -- raising it would buy nothing.
 */
export const MAX_VOLUME = 2;

/** The chime's full-scale peak at volume 1.0 (a bare oscillator, so 1.0 is full scale). */
export const CHIME_PEAK_GAIN = 0.5;

/**
 * The volume every audio path should actually use.
 *
 * Mute is deliberately NOT a volume of 0 stored in `volume`: the operator
 * wants their level back when they unmute, and a mute that eats the setting
 * is a mute nobody uses twice. So the level is kept and this is the only
 * place the two are combined -- which is the whole safety of it. Every
 * consumer already funnels through `speechOptsFrom()` or `useAudio()`, so
 * putting the combination here means a new audio path cannot be silently
 * born un-mutable.
 */
export function effectiveVolume(audio: { volume: number; muted?: boolean }): number {
  return audio.muted ? 0 : clampVolume(audio.volume);
}

export function clampVolume(v: number): number {
  if (!Number.isFinite(v)) return 1;
  return Math.min(MAX_VOLUME, Math.max(0, v));
}

/**
 * What to put on an HTMLMediaElement. Never above 1 -- the setter throws,
 * and a throw here would take out the whole utterance.
 *
 * This is now the WHOLE of the clip path's level control: a request above
 * 100% arrives at the element as 100% and plays there. Nothing routes the
 * excess anywhere, by design.
 */
export function elementVolume(v: number): number {
  return Math.min(1, clampVolume(v));
}

/** What `speechSynthesis` can actually honour. Above 1 is clamped anyway. */
export function utteranceVolume(v: number): number {
  return Math.min(1, clampVolume(v));
}

/** Chime envelope peak, kept inside full scale so the tone cannot clip. */
export function chimePeak(v: number): number {
  return Math.min(1, CHIME_PEAK_GAIN * clampVolume(v));
}
